# Site settings
title: "Visualisateur Poppy Ergo Jr"
description: "Visualisateur WebGL pour le robot Poppy Ergo Jr."

# Build settings
markdown: kramdown

include: [ "_pages" ]

exclude: [
  "Gemfile",
  "Gemfile.lock",
  "Rakefile",
  "README.md",
  "LICENSE.md",
  "vendor"
]

docs_url: "https://docs.poppy-project.org/fr/getting-started/visualize.html"
scratch_url: "https://scratch.poppy-project.org/"
